# Generated by Django 3.0.7 on 2021-06-08 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_auto_20210607_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='income',
            old_name='category',
            new_name='source',
        ),
    ]
